// pages/index.vue
<template>
  <div>
    <div class="pure-form pure-g">
      <fieldset>
        <legend class="pure-u-1">Edit</legend>
        <input
          v-model.number="edit_x"
          type="number"
          min="0"
          placeholder="x"
          class="pure-u-1-12"
        />
        <input
          v-model.number="edit_y"
          type="number"
          min="0"
          placeholder="y"
          class="pure-u-1-12"
        />
        <input
          v-model="edit_data"
          type="text"
          placeholder="value or formula"
          class="pure-u-5-6"
          :disabled="is_valid_position == false"
        />
      </fieldset>
    </div>
    <div class="pure-form">
      <fieldset>
        <legend>Insert / Remove</legend>
        <select v-model="row_or_column" class="pure-input-1-4">
          <option disabled value="">Please Select</option>
          <option>Row</option>
          <option>Column</option>
        </select>
        <input
          v-model.number="insert_remove_pos"
          type="number"
          min="0"
          placeholder="position"
          class="pure-input-1-4"
        />
        <button class="pure-button" :disabled="!is_insertable">Insert</button>
        <button class="pure-button" :disabled="!is_removable">Remove</button>
        <p v-if="is_insertable">
          Insert / Remove a {{ row_or_column }} at {{ insert_remove_pos }}
        </p>
      </fieldset>
    </div>
    <table class="pure-table pure-table-bordered">
      <tbody>
        <tr v-for="(column, y) in table" :key="y">
          <td
            v-for="(item, x) in column"
            :key="x"
            :title="'(' + x + ', ' + y + ')'"
            @click="
              edit_x = x
              edit_y = y
              if (row_or_column === 'Row') {
                insert_remove_pos = y
              } else if (row_or_column === 'Column') {
                insert_remove_pos = x
              }
            "
          >
            {{ item }}
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
  data: () => ({
    edit_x_internal: 0,
    edit_y_internal: 0,
    x_size: 5,
    y_size: 5,
    edit_data_internal: '0',
    is_valid_position: true,
    insert_or_remove: '',
    row_or_column: '',
    insert_remove_pos: 0,
    table: [
      ['0', '1', '2', '3', '4'],
      ['5', '6', '7', '8', '9'],
      ['10', '11', '12', '13', '14'],
      ['15', '16', '17', '18', '19'],
      ['20', '21', '22', '23', '24'],
    ],
  }),
  computed: {
    edit_x: {
      get() {
        return this.edit_x_internal
      },
      set(value: number) {
        this.update_edit_pos(value, this.edit_y)
      },
    },
    edit_y: {
      get() {
        return this.edit_y_internal
      },
      set(value: number) {
        this.update_edit_pos(this.edit_x, value)
      },
    },
    edit_data: {
      get() {
        return this.edit_data_internal
      },
      set(value: string) {
        this.edit_data_internal = value

        if (this.is_valid_position) {
          this.table[this.edit_x][this.edit_y] = value
        }
      },
    },
    is_insertable() {
      return (
        this.row_or_column !== '' &&
        Number.isInteger(this.insert_remove_pos) &&
        this.insert_remove_pos >= 0 &&
        this.insert_remove_pos <=
          (this.row_or_column === 'row' ? this.y_size : this.x_size)
      )
    },
    is_removable() {
      return (
        this.row_or_column !== '' &&
        Number.isInteger(this.insert_remove_pos) &&
        this.insert_remove_pos >= 0 &&
        this.insert_remove_pos <
          (this.row_or_column === 'row' ? this.y_size : this.x_size)
      )
    },
  },
  methods: {
    update_edit_pos(x: number, y: number) {
      this.edit_x_internal = x
      this.edit_y_internal = y

      if (
        !Number.isInteger(x) ||
        !Number.isInteger(y) ||
        this.edit_x < 0 ||
        this.x_size <= this.edit_x ||
        this.edit_y < 0 ||
        this.y_size <= this.edit_y
      ) {
        this.edit_data_internal = ''
        this.is_valid_position = false
      } else {
        this.edit_data_internal = this.table[this.edit_x][this.edit_y]
        this.is_valid_position = true
      }
    },
  },
})
</script>

// pages/index.tsx
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import init, {
  get_x_size, get_y_size, get_raw_item, get_calculated_item, update_item,
  insert_x, insert_y, remove_x, remove_y
} from '../pkg/csvx_client.js';

var wasm = undefined;

function loadTable(xSize: number, ySize: number) {
  let table = [] as string[][];
  for (let y = 0; y < ySize; y++) {
    let row = [];
    for (let x = 0; x < xSize; x++) {
      row.push(get_calculated_item(x, y));
    }
    table.push(row);
  }
  return table
}

export default function Home() {
  const [isLoaded, setIsLoaded] = useState(false);

  const [xSize, setXSize] = useState(0);
  const [ySize, setYSize] = useState(0);
  const [table, setTable] = useState([] as string[][]);

  const [editX, setEditX] = useState(0);
  const [editY, setEditY] = useState(0);
  const [editFormula, setEditFormula] = useState('');
  const [isValidPosition, setIsValidPosition] = useState(false);

  const [rowOrColumn, setRowOrColumn] = useState('');
  const [insertRemovePos, setInsertRemovePos] = useState(0);

  useEffect(() => {
    if (isLoaded) {
      setEditFormula(get_raw_item(editX, editY));
    }
  }, [editX, editY, table])

  useEffect(() => {
    setIsValidPosition(
      isLoaded &&
      0 <= editX &&
      editX < xSize &&
      0 <= editY &&
      editY < ySize);
  }, [table, editX, editY, xSize, ySize]);

  useEffect(() => {
    init('/csvx.wasm').then(v => {
      console.log('Loaded')
      wasm = v;
      setIsLoaded(true);
      setXSize(get_x_size());
      setYSize(get_y_size());
    });
  }, []);


  useEffect(() => {
    setTable(loadTable(xSize, ySize));
  }, [xSize, ySize]);

  useEffect(() => {
    if (table.length != 0 &&
      table[0].length != 0 &&
      0 <= editX &&
      editX < xSize &&
      0 <= editY &&
      editY < ySize) {
      update_item(editX, editY, editFormula);
      setTable(loadTable(xSize, ySize));
    }
  }, [editFormula])

  return (
    <div>
      <Head>
        <title>Home | CSVX</title>
        <meta name='description' content='Comma-Separated Values eXtended' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='pure-form pure-g'>
        <fieldset>
          <legend className='pure-u-1'>Edit</legend>
          <input
            value={editX}
            onChange={e => {
              setEditX(Number.parseInt(e.target.value))
            }}
            type='number'
            min='0'
            placeholder='x'
            className='pure-u-1-12'
          />
          <input
            value={editY}
            onChange={e => {
              setEditY(Number.parseInt(e.target.value))
            }}
            type='number'
            min='0'
            placeholder='y'
            className='pure-u-1-12'
          />
          <input
            value={editFormula}
            onChange={e => {
              setEditFormula(e.target.value)
            }}
            type='text'
            placeholder='value or formula'
            className='pure-u-5-6'
            disabled={!isValidPosition}
          />
        </fieldset>
      </div>
      <div className='pure-form'>
        <fieldset>
          <legend>Insert / Remove</legend>
          <select value={rowOrColumn} onChange={e => setRowOrColumn(e.target.value)} className='pure-input-1-4'>
            <option disabled value=''>Please Select</option>
            <option>Row</option>
            <option>Column</option>
          </select>
          <input
            value={insertRemovePos}
            onChange={e => setInsertRemovePos(Number.parseInt(e.target.value))}
            type='number'
            min='0'
            placeholder='position'
            className='pure-input-1-4'
          />
          <button className='pure-button'
            disabled={rowOrColumn === '' ||
              insertRemovePos < 0 ||
              (rowOrColumn === 'Row' ? ySize : xSize) < insertRemovePos}
            onClick={() => {
              if (rowOrColumn == 'Row') {
                insert_y(insertRemovePos);
              }
              else {
                insert_x(insertRemovePos);
              }
              setXSize(get_x_size());
              setYSize(get_y_size());
            }}>Insert</button>
          <button className='pure-button'
            disabled={rowOrColumn === '' ||
              insertRemovePos < 0 ||
              (rowOrColumn === 'Row' ? ySize : xSize) <= insertRemovePos ||
              (rowOrColumn === 'Row' ? ySize : xSize) == 1}
            onClick={() => {
              if (rowOrColumn == 'Row') {
                remove_y(insertRemovePos);
              }
              else {
                remove_x(insertRemovePos);
              }
              setXSize(get_x_size());
              setYSize(get_y_size());
            }}>Remove</button>
          <p>Insert / Remove a {rowOrColumn} at {insertRemovePos}</p>
        </fieldset>
      </div>
      <table className='pure-table pure-table-bordered'>
        <tbody>
          {table.map(
            (column, y) =>
              <tr key={y}>
                {column.map((item, x) =>
                  <td key={x}
                    title={'(' + x + ',' + y + ')'}
                    onClick={() => {
                      setEditX(x)
                      setEditY(y)
                      if (rowOrColumn === 'Row') {
                        setInsertRemovePos(y)
                      } else if (rowOrColumn === 'Column') {
                        setInsertRemovePos(x)
                      }
                    }}
                  >
                    {item}
                  </td>
                )}
              </tr>
          )}
        </tbody>
      </table>
    </div>
  )
}
